// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhJrSxx3WrKMeWjSVB8nAu9K8EVWIGI9o',
    appId: '1:609536378901:web:272495ad1d5c828fd6e61c',
    messagingSenderId: '609536378901',
    projectId: 'istanbul-guide-a5969',
    authDomain: 'istanbul-guide-a5969.firebaseapp.com',
    storageBucket: 'istanbul-guide-a5969.firebasestorage.app',
    measurementId: 'G-VYBMDN06DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiF69_vHnLXTGVV94iAANy7C87-n7AOz4',
    appId: '1:609536378901:android:6662767c88e03553d6e61c',
    messagingSenderId: '609536378901',
    projectId: 'istanbul-guide-a5969',
    storageBucket: 'istanbul-guide-a5969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8vHIwq6Wqsmu5KMY7WVkvYKY4sXAG3k',
    appId: '1:609536378901:ios:ab9266fbda55962dd6e61c',
    messagingSenderId: '609536378901',
    projectId: 'istanbul-guide-a5969',
    storageBucket: 'istanbul-guide-a5969.firebasestorage.app',
    iosBundleId: 'com.example.istanbulguidetwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8vHIwq6Wqsmu5KMY7WVkvYKY4sXAG3k',
    appId: '1:609536378901:ios:ab9266fbda55962dd6e61c',
    messagingSenderId: '609536378901',
    projectId: 'istanbul-guide-a5969',
    storageBucket: 'istanbul-guide-a5969.firebasestorage.app',
    iosBundleId: 'com.example.istanbulguidetwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhJrSxx3WrKMeWjSVB8nAu9K8EVWIGI9o',
    appId: '1:609536378901:web:917661961716c534d6e61c',
    messagingSenderId: '609536378901',
    projectId: 'istanbul-guide-a5969',
    authDomain: 'istanbul-guide-a5969.firebaseapp.com',
    storageBucket: 'istanbul-guide-a5969.firebasestorage.app',
    measurementId: 'G-54YHETWELC',
  );

}